import type { GetServerSideProps, NextPage } from "next";
import type { MemberData, MemberRecap } from "~/types";
import { createApiInstance, getMemberData, getMemberRecap, login } from "~/api";

import Head from "next/head";
import { useRouter } from "next/router";

interface DriverPageProps {
  memberData: MemberData;
  //   memberProfile: any;
  memberRecap: MemberRecap;
}

const Driver: NextPage<DriverPageProps> = ({ memberData, memberRecap }) => {
  const router = useRouter();
  const { iracingId } = router.query;

  console.log({ iracingId, memberData, memberRecap });

  return (
    <>
      <Head>
        <title>Season summary</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen flex-col items-center justify-center bg-slate-800 text-slate-100">
        {iracingId}
      </main>
    </>
  );
};

// TODO: Add await all
export const getServerSideProps: GetServerSideProps = async ({
  params,
  res,
}) => {
  try {
    const { iracingId } = params as { iracingId: string };

    const apiInstance = createApiInstance();
    await login(apiInstance);
    const memberData = await getMemberData(apiInstance, iracingId);
    // const memberProfile = await getMemberProfile(apiInstance, iracingId);
    const memberRecap = await getMemberRecap(apiInstance, iracingId);

    return {
      props: {
        memberData,
        // memberProfile,
        memberRecap,
      },
    };
  } catch {
    res.statusCode = 404;
    return {
      props: {},
    };
  }
};

export default Driver;
