import type { GetServerSideProps, NextPage } from "next";
import type { MemberData, MemberRecap } from "~/types";
import { createApiInstance, getMemberData, getMemberRecap, login } from "~/api";

import FavoriteCar from "~/components/FavoriteCar";
import FavoriteTrack from "~/components/FavoriteTrack";
import Head from "next/head";
import Header from "~/displays/Driver/Header";
import ShortRecap from "~/displays/Driver/ShortRecap";
import { useRouter } from "next/router";

interface DriverPageProps {
  memberData: MemberData;
  memberRecap: MemberRecap;
}

const Driver: NextPage<DriverPageProps> = ({ memberData, memberRecap }) => {
  const router = useRouter();
  const { iracingId } = router.query;

  console.log({ iracingId, memberData, memberRecap });

  return (
    <>
      <Head>
        <title>Season summary</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen flex-col items-center bg-slate-800 p-2 text-slate-100">
        <div className="flex w-[90%] flex-col gap-2">
          <Header memberData={memberData} />
          <ShortRecap memberRecap={memberRecap} />
          <FavoriteCar favoriteCar={memberRecap.stats.favoriteCar} />
          <FavoriteTrack favoriteTrack={memberRecap.stats.favoriteTrack} />
        </div>
      </main>
    </>
  );
};

// TODO: Add await all
export const getServerSideProps: GetServerSideProps = async ({
  params,
  res,
}) => {
  try {
    const { iracingId } = params as { iracingId: string };

    const apiInstance = createApiInstance();
    await login(apiInstance);
    const memberData = await getMemberData(apiInstance, iracingId);
    // const memberProfile = await getMemberProfile(apiInstance, iracingId);
    const memberRecap = await getMemberRecap(apiInstance, iracingId);

    return {
      props: {
        memberData,
        // memberProfile,
        memberRecap,
      },
    };
  } catch {
    res.statusCode = 404;
    return {
      props: {},
    };
  }
};

export default Driver;
