import { type NextPage } from "next";
import Head from "next/head";
import DriverList from "~/components/DriverList";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Season summary</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen flex-col items-center justify-center bg-slate-800 text-slate-100">
        <DriverList />
      </main>
    </>
  );
};

export default Home;
